name: 'Banner Checker'
description: 'Validate your files begin with a specific banner for compliance reasons'
author: 'Antonios Katopodis'
inputs:
  banner:
    required: true
    description: 'The banner to check for each file'
  path:
    required: true
    description: 'The path to scan for the files'
  include-extensions:
    required: false
    description: 'Scan only those specific extensions'
  exclude-extensions:
    required: false
    description: 'Don't scan those specific extensions'
  warning:
    required: false
    description: "If set to true will output the missing banners as warnings instead of erros"
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
